baseURL: 'http://wator.it/'
copyright: Konrad Wątor
languages:
  en:
    title: Konrad Wątor
    languageName: English
  pl:
    title: Konrad Wątor
    languageName: Polski
    weight: 2
theme: konrad
enableEmoji: true
