baseURL: 'http://wator.it/'
copyright: Konrad Wątor
languages:
  en:
    title: C'est moi Leclerc
    languageName: English
  pl:
    title: To ja Leklerk
    languageName: Polski
    weight: 2
theme: konrad
enableEmoji: true
